git:
  submodules: false
language: perl
perl:
  - "5.26"
  - "5.14"
  - "5.8"
before_install: git submodule update --init
install: "make test-deps"
script: "make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "ircs://irc.suikawiki.org:6679#mechanize"
    use_notice: true
env:
  global:
    secure: "JEE76Kb9vVrUdScT7EQ7DWUIDr87LLXu4MyGpqL37TMS+8k0p1Db22HSgyDhFz1ZFOn0qoqKH5xfeFgHorKteBLdPieEftCFf+2ZkwfAWgsyOJCPHzBOzJhovYcozf89QY9nVdbfb01gyzKRk6VGAtDvNKoAwAe3SmnTxt8jWPH8LDcgWU+3vleBw6sgKYr9gX5XgYQBz9OrG9S4X4R4DoSvquZtn2UUtl9ujpP0/ieVpV5XKIsTlVF6jG1YnEeMdVlvYAfJvKsRvKgREUC772PNrRFaFQtDwflzMrsmHxGMLVI74zTsYqYe16HjLpTH9golJizVU1qXobm/YzvE1FGRctHiSI+qzM20zAF//EOEcM1JwEXWK3TIXebYQSMEmSJlXdWAzXYGVXHPK0q2mE8lGHJskPXwPom27FNQ8I7DOsWdc/cLaCLpZ6Ok+Hm2lFOFCA2Qr2svpM2jYAyMUg3q1riIRY5uwwnfNYePxzDYtVDE8oNFVH+ZQHFxYj7M+IeRWpymKGtxj3+J8w81iakLg6Q5xoifhcGbUAaFwvjIE9Bs6bAvyLs7+iKwpG195M2i4QZ9GLVMUxR6w0XKesjGpiojWBj+mksuRXIygw3n5SX0qZ/ES9p+gpsmHZLgMTgn2fQsoFomRYCpSMoS8iItIuyDiV1iIKi08ERI6i0="
after_success:
  - curl -s -S -L https://gist.githubusercontent.com/wakaba/9970857/raw/travis-merger.pl | perl
